#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace AccountValidation.Plugins.EarlyBoundEntities
{
	
	
	/// <summary>
	/// Represents a source of entities bound to a Dataverse service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	public partial class OrgContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		public OrgContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="AccountValidation.Plugins.EarlyBoundEntities.Account"/> entities.
		/// </summary>
		public System.Linq.IQueryable<AccountValidation.Plugins.EarlyBoundEntities.Account> AccountSet
		{
			get
			{
				return this.CreateQuery<AccountValidation.Plugins.EarlyBoundEntities.Account>();
			}
		}
	}
}
#pragma warning restore CS1591
